[workspace]
members = [
    "crates/du-blueprint",
    "crates/renderer-app",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.2.1"
authors = []
license = ""

[workspace.dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
thiserror = "1.0"
once_cell = "1.19"
parking_lot = "0.12"

[profile.release]
debug = true
